### ISSUE TITLE
BasicBlock is defined twice, overwriting previous definition

### ISSUE THREAD

**Issue by ffund** [kokoedwin/SOR23-Using-Reproducibility-in-Machine-Learning-Education#5]
We defined a `BasicBlock` twice - once in a ResNet and once in a WideResNet - and the second definition overwrites the first.

Then when we try to use a ResNet, it raises the error - 

```
AttributeError: type object 'BasicBlock' has no attribute 'expansion'
```

**Comment by kokoedwin** [comment]
I have verified that it can run for the WideResNet model
